<a href="https://colab.research.google.com/github/victoraccete/omdena_streamlit_workshop/blob/main/Very_simple_titanic_ML_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from joblib import dump, load

# Dataset:
Full version: vhttps://www.kaggle.com/c/titanic/data?select=train.csv  
Reduced version (the one we're using here): https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/problem12.html


In [13]:
titanic = pd.read_csv("https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv")
titanic = titanic.drop(columns="Name")
titanic

Survived  Pclass  ... Parents/Children Aboard     Fare
0           0       3  ...                       0   7.2500
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
4           0       3  ...                       0   8.0500
..        ...     ...  ...                     ...      ...
882         0       2  ...                       0  13.0000
883         1       1  ...                       0  30.0000
884         0       3  ...                       2  23.4500
885         1       1  ...                       0  30.0000
886         0       3  ...                       0   7.7500

[887 rows x 7 columns]

In [21]:
titanic['Parents/Children Aboard'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [23]:
titanic = pd.get_dummies(titanic)
titanic.head()

Survived  Pclass   Age  ...     Fare  Sex_female  Sex_male
0         0       3  22.0  ...   7.2500           0         1
1         1       1  38.0  ...  71.2833           1         0
2         1       3  26.0  ...   7.9250           1         0
3         1       1  35.0  ...  53.1000           1         0
4         0       3  35.0  ...   8.0500           0         1

[5 rows x 8 columns]

In [24]:
inputs = titanic.iloc[:, 1:]
inputs.head()

Pclass   Age  Siblings/Spouses Aboard  ...     Fare  Sex_female  Sex_male
0       3  22.0                        1  ...   7.2500           0         1
1       1  38.0                        1  ...  71.2833           1         0
2       3  26.0                        0  ...   7.9250           1         0
3       1  35.0                        1  ...  53.1000           1         0
4       3  35.0                        0  ...   8.0500           0         1

[5 rows x 7 columns]

In [31]:
labels = titanic.iloc[:, 0]
labels.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [32]:
rf_clf = RandomForestClassifier(n_estimators=50)
rf_clf.fit(inputs.values, labels.values)
scores = cross_val_score(rf_clf, inputs, labels, cv=20)
scores

array([0.68888889, 0.82222222, 0.71111111, 0.8       , 0.75555556,
       0.73333333, 0.88888889, 0.81818182, 0.93181818, 0.86363636,
       0.90909091, 0.77272727, 0.77272727, 0.90909091, 0.77272727,
       0.77272727, 0.79545455, 0.84090909, 0.81818182, 0.93181818])

In [33]:
scores.mean()

0.8154545454545454

In [46]:
rf_clf.predict(inputs.iloc[1:2, :].values)

array([1])

In [50]:
dump(rf_clf, 'rf.joblib')

['rf.joblib']

In [49]:
clf = load('rf.joblib')
clf.predict(inputs.iloc[1:2, :].values)

array([1])